# Generated by Django 6.0 on 2026-01-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0002_remove_contactinfo_house_contactinfo_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_for_user', to='auth.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='permission_for_user', to='auth.permission', verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
