# Generated by Django 5.2.5 on 2026-01-06 19:13

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_customuser_user_type_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Определяет, следует ли считать этого пользователя активным.Снимите этот флажок вместо удаления учетных записей.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти на этот сайт администратора.', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем пользователя уже существует.'}, help_text='Требования. Не более 150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Псевдоним'),
        ),
    ]
