# Generated by Django 5.2.5 on 2026-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
