# Generated by Django 5.2.5 on 2026-01-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_additionresult_delete_productprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionResult',
        ),
    ]
