# Generated by Django 5.2.5 on 2026-01-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_additionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказанные позиции'),
        ),
    ]
