# Generated by Django 5.2.5 on 2026-01-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_order_ordered_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ['parameter'], 'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Параметры продукта'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
    ]
