# Generated by Django 5.2.5 on 2026-01-12 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_remove_orderitem_unique_order_item_orderitem_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="shops",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                to="backend.shop",
                verbose_name="Магазины",
            ),
        ),
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirm_email_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_items",
                to="backend.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_items",
                to="backend.productinfo",
                verbose_name="Информация о продукте",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="backend.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="product",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_info",
                to="backend.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_info",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="parameter",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_parameters",
                to="backend.parameter",
                verbose_name="Параметр",
            ),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="product_info",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_parameters",
                to="backend.productinfo",
                verbose_name="Информация о продукте",
            ),
        ),
    ]
