"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from os import path
from pathlib import Path
from django.core.management.utils import get_random_secret_key  # Импортирована функция случайного секретного ключа

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key  # Удален секретный ключ по умолчанию и заменен на результат работы функции

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv("DEBUG", default=0)) # Значение в файле переменных .env

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS").split(",") # Значение в файле переменных .env

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:1337",
    "http://localhost:1337",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'drf_spectacular',

    'backend',           # Добавлено приложение
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',

    'easy_thumbnails',
    'filer',
    'mptt',

    'debug_toolbar',

    'baton',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.vk',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [path.join(BASE_DIR, 'backend', 'templates', 'backend')], # используем каталог шаблонов на уровне проекта
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Django Debug Toolbar
INTERNAL_IPS = ["127.0.0.1", "localhost" , "[::1]", "0.0.0.0"]

WSGI_APPLICATION = 'orders.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Внесены настройки базы данных postgresql из файла .env
DATABASES = {
    'default': {
        "ENGINE": os.getenv("DJANGO_POSTGRES_ENGINE", 'django.db.backends.postgresql_psycopg2'),
        "NAME": os.getenv("DJANGO_POSTGRES_DB", 'diplom_db'),
        "USER": os.getenv("DJANGO_POSTGRES_USER", "diplom_user"),
        "PASSWORD": os.getenv("DJANGO_POSTGRES_PASSWORD", "diplom_secret"),
        "HOST": os.getenv("DJANGO_POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("DJANGO_POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'backend.CustomUser' # новая модель пользователя вместо встроенной модели User

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'

# То как статический файл будет отображаться в url
# По какому пути можно будет найти static файлы
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# Аналогично с media файлами
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"





# Для TokenAuthentication
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 40,

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],

    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/minute',  # Для неаутентифицированных пользователей
        'user': '500/minute',  # Для аутентифицированных пользователей
    },

    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

AUTHENTICATION_BACKENDS = (
    # 'social_core.backends.google.GoogleOAuth2',  # Для Google
    # 'social_core.backends.facebook.FacebookOAuth2',  # Для Facebook (если нужно)
    'django.contrib.auth.backends.ModelBackend',  # Стандартная авторизация
    'allauth.account.auth_backends.AuthenticationBackend',
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://localhost:6379',
    }
}

#Client email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SITE_ID = 1
EMAIL_HOST = os.getenv("EMAIL_HOST",)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER",)
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD",)
EMAIL_PORT = os.getenv("EMAIL_PORT",)
EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

SOCIALACCOUNT_FORMS = {'signup': 'backend.forms.MyCustomSignupForm'}

#Redis and celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BROKER_TRANSPORT_OPTION = {'visibility_timeout': 3600}
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'

#Email verification settings
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGOUT_REDIRECT_URL ='/accounts/login/'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = '/api/v1/'
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*',]
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = {'email'}
ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 60
ACCOUNT_RATE_LIMITS = False
